
version: '3.5'

services:
  web:
    build:
      context: .
    command: ["mix", "phx.server"]
    ports:
      - "80:4000"
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - db

  ai:
    build:
      context: ./ai
    ports:
      - 8000:8000
    env_file: .env
    volumes:
      - ./ai:/app
    depends_on:
      - web

  db:
    image: postgres:11.1
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file: .env
    ports:
      - "5432:5432"

volumes:
  redis-data:
  pg-data:
