apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "chart.fullname" . }}-web-config"
  labels:
    app.kubernetes.io/name: "{{ include "chart.fullname" . }}-web-config"
    helm.sh/chart: {{ include "chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  MIX_ENV: "prod"
  PORT: "4000"
  HOST: "arrows.gavr.games"
  POSTGRES_HOST: "46.101.253.11"